name: GiveAll
version: 1.0.0
description: GiveAll Plugin
author: extended_clip
authors: [cj89898]
main: com.extendedclip.giveall.GiveAll
commands:
  giveall:
    description: Give All
    usage: '/giveall <item/hand>(amount) (message)'
    aliases: [ga]

permissions:
  giveall.give:
    description: Give All
    default: op